name: CI

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run markdown lint
        run: |
          npm install remark-cli remark-preset-lint-consistent
          npx remark . --use remark-preset-lint-consistent --report vfile-reporter-json > remark-lint-report.json

      - uses: actions/upload-artifact@v3
        with:
          name: remark-lint-report
          path: remark-lint-report.json
